# ==============================================================================
# Run State: Soft-Lock + parent_run_id Mechanism
# ==============================================================================
# Implements the REDCap dev/production pattern: a pakhom run lives in one of
# two states, and methodology cannot silently change between them.
#
#   active     -- pipeline is running. run_metadata.json has
#                 is_finalized = FALSE. Methodology can be changed mid-
#                 pipeline only by re-running with parent_run_id (auto-
#                 generated by clone_run_with_new_mode).
#   finalized  -- terminal state after the report is generated.
#                 is_finalized = TRUE; finalized_at is set. The
#                 methodology declaration is now frozen for the canonical
#                 output. Any future change to methodology must fork a
#                 new run via clone_run_with_new_mode (which writes
#                 parent_run_id into the new run's metadata).
#
# The PROSPERO and REDCap precedent is the methodological motivation:
# qualitative-research methodology is the kind of decision that needs an
# explicit, auditable trail. Silent re-declaration is exactly the
# AsPredicted / questionable-research-practice failure mode that ACs 5
# and 6 commit pakhom against.
# ==============================================================================

#' Schema version for run_metadata.json
#'
#' Consumers (summarize_audit_log(), planned replay tooling) read this to gate
#' back-compat reads. Bumped when the metadata schema changes
#' incompatibly.
#' @keywords internal
.RUN_METADATA_SCHEMA_VERSION <- "1.0.0"

#' Prompt-template generation marker
#'
#' Stamped into \code{run_metadata.json$prompt_template_version} so a
#' future replayer can detect when a loaded cache was produced under a
#' different prompt-template generation. Bump this value whenever a
#' prompt rewrite shifts the AI-visible character offsets or the
#' response schema.
#'
#' The current generation wraps entry text in an
#' \code{<entry_text>...</entry_text>} fence with verbatim text (offset
#' arithmetic preserved through \code{.escape_entry_text_fence}); an
#' earlier generation JSON-escaped an \code{Entry text:} wrapping.
#' @keywords internal
.PROMPT_TEMPLATE_VERSION <- "1.0.0"

#' Path to the run-metadata JSON for a run directory
#' @keywords internal
.run_metadata_path <- function(run_dir) {
  file.path(run_dir, "run_metadata.json")
}

#' Read and parse run_metadata.json for a run directory
#'
#' Returns NULL when the file is missing (e.g., a run directory created by a
#' very old pakhom version, or a partially-initialized run that crashed
#' before run_metadata.json was written). Returns NULL on parse error too,
#' so callers can treat "no metadata" and "corrupt metadata" identically
#' (both mean: fall back to the no-prior-state code path). Errors do warn
#' so the user knows the file existed but couldn't be read.
#'
#' @param run_dir Path to a run output directory.
#' @return Named list of run metadata, or NULL when missing/unreadable.
#' @export
read_run_metadata <- function(run_dir) {
  path <- .run_metadata_path(run_dir)
  if (!file.exists(path)) return(NULL)
  tryCatch(
    jsonlite::read_json(path, simplifyVector = TRUE),
    error = function(e) {
      log_warn("Could not parse run_metadata.json at {path}: {e$message}")
      NULL
    }
  )
}

#' Write run metadata for a run directory
#'
#' Writes \code{metadata} to \code{run_metadata.json} in JSON form.
#' Atomic-ish: writes to a temp file first, then renames. If the
#' atomic-rename fails (e.g., cross-filesystem move), falls back to a
#' direct write -- the failure modes are not silent because both branches
#' log on error.
#'
#' @param run_dir Path to a run output directory (must exist).
#' @param metadata Named list to serialize.
#' @return TRUE on success, FALSE on failure (warning logged).
#' @keywords internal
.write_run_metadata <- function(run_dir, metadata) {
  if (!dir.exists(run_dir)) {
    log_warn("run_dir does not exist: {run_dir}")
    return(FALSE)
  }
  path <- .run_metadata_path(run_dir)
  tmp  <- paste0(path, ".tmp")
  ok <- tryCatch({
    jsonlite::write_json(metadata, tmp, pretty = TRUE, auto_unbox = TRUE)
    TRUE
  }, error = function(e) {
    log_warn("Failed to write run metadata: {e$message}")
    FALSE
  })
  if (!ok) return(FALSE)
  ok <- tryCatch({
    file.rename(tmp, path)
  }, error = function(e) FALSE)
  if (!isTRUE(ok)) {
    # Fall back to a direct write (e.g., cross-filesystem temp/dest)
    ok <- tryCatch({
      jsonlite::write_json(metadata, path, pretty = TRUE, auto_unbox = TRUE)
      TRUE
    }, error = function(e) {
      log_warn("Direct write of run metadata failed: {e$message}")
      FALSE
    })
    if (file.exists(tmp)) tryCatch(file.remove(tmp), error = function(e) NULL)
  }
  ok
}

#' Initialize the run-metadata record for a new (or resumed) run
#'
#' Builds the run_metadata.json content from the supplied run details and
#' writes it to \code{run_dir}. Idempotent on resume: when
#' \code{run_metadata.json} already exists, returns the existing metadata
#' WITHOUT overwriting (so finalized markers / parent_run_id aren't
#' clobbered by a casual re-init). To recreate, delete the file first.
#'
#' @param run_dir Path to the run directory.
#' @param run_id Stable run identifier (often the basename of \code{run_dir}).
#' @param methodology_mode Character: the declared mode for this run.
#' @param parent_run_id Optional character: when this run is a fork of a
#'   prior run with a different methodology, the parent's run_id.
#' @param mode_changed_from Optional character: the methodology mode of
#'   the parent run (when forked). NULL when this is a fresh run.
#' @param ... Additional fields written verbatim into run_metadata.json
#'   (e.g., \code{provider = "anthropic"}, \code{study_name = "..."}).
#' @return The metadata list (existing or newly written).
#' @export
init_run_state <- function(run_dir, run_id, methodology_mode,
                            parent_run_id = NULL,
                            mode_changed_from = NULL,
                            ...) {
  validate_methodology_mode(methodology_mode, allow_null = FALSE,
                              caller = "init_run_state")
  if (!dir.exists(run_dir)) {
    dir.create(run_dir, recursive = TRUE, showWarnings = FALSE)
  }
  existing <- read_run_metadata(run_dir)
  if (!is.null(existing)) {
    log_debug("init_run_state: {run_dir} already has run_metadata.json; preserving it")
    return(existing)
  }

  now_iso <- format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z", tz = "UTC")
  meta <- list(
    run_id              = run_id,
    methodology_mode    = methodology_mode,
    parent_run_id       = parent_run_id,
    mode_changed_from   = mode_changed_from,
    mode_locked_at      = now_iso,
    is_finalized        = FALSE,
    finalized_at        = NULL,
    created_at          = now_iso,
    schema_version      = .RUN_METADATA_SCHEMA_VERSION,
    # Stamp the prompt-template generation into run_metadata so a
    # future replayer can detect when a loaded cache was produced
    # under a different prompt template. The most recent
    # generation-shift moved from a JSON-escaped wrapping to the
    # <entry_text> fence. Future prompt rewrites should bump this value.
    prompt_template_version = .PROMPT_TEMPLATE_VERSION
  )
  extra <- list(...)
  for (nm in names(extra)) meta[[nm]] <- extra[[nm]]

  .write_run_metadata(run_dir, meta)
  meta
}

#' Check whether a run directory is finalized
#'
#' A finalized run cannot have its methodology silently re-declared. Per
#' AC5 (soft-lock with audit trail; methodology change creates new run),
#' callers check this flag before mutating methodology-affecting state on
#' a prior run; if TRUE, they fork via \code{\link{clone_run_with_new_mode}}.
#'
#' Returns FALSE for a missing run_metadata.json -- "no metadata" means
#' "not finalized" by definition (the canonical record doesn't exist
#' yet, so no claim has been made).
#'
#' @param run_dir Path to a run output directory.
#' @return Logical scalar.
#' @export
is_run_finalized <- function(run_dir) {
  meta <- read_run_metadata(run_dir)
  if (is.null(meta)) return(FALSE)
  isTRUE(meta$is_finalized)
}

#' Mark a run as finalized
#'
#' Sets \code{is_finalized = TRUE} and \code{finalized_at} on the run's
#' metadata. Idempotent: re-finalizing a finalized run is a no-op (logs
#' debug and returns the existing metadata unchanged).
#'
#' Called once per run -- typically as the last step of \code{run_analysis}
#' after the report is generated. Per AC5, finalization is the moment
#' methodology is locked for the canonical output.
#'
#' @param run_dir Path to a run output directory.
#' @return The updated metadata list, or NULL if the run has no metadata
#'   to finalize.
#' @export
finalize_run <- function(run_dir) {
  meta <- read_run_metadata(run_dir)
  if (is.null(meta)) {
    log_warn("finalize_run: no run_metadata.json at {run_dir}; nothing to finalize")
    return(NULL)
  }
  if (isTRUE(meta$is_finalized)) {
    log_debug("finalize_run: {run_dir} already finalized; no-op")
    return(meta)
  }
  meta$is_finalized <- TRUE
  # UTC TZ for cross-file ordering consistency
  # with created_at (init_run_state line 162) + ai_decisions.jsonl
  # + live/*.json + fabrication_log.csv. Previously this
  # field was the only one in run_metadata.json still using local
  # TZ -- a self-inconsistency that was later caught and fixed.
  meta$finalized_at <- format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z", tz = "UTC")
  .write_run_metadata(run_dir, meta)
  log_info("Run finalized: {run_dir}")
  meta
}

#' Detect a methodology mismatch between a config and an existing run
#'
#' Compares the methodology mode in \code{config} against the
#' \code{methodology_mode} stored in \code{run_dir}'s run_metadata.json.
#' Used at pipeline start to decide between resume (modes match), error
#' (modes differ + run finalized), or fork (modes differ + run still
#' active and the user explicitly requested a fork).
#'
#' @param run_dir Path to a run output directory.
#' @param config A ThematicConfig (or list with a \code{methodology$mode}
#'   slot) representing the methodology declared for the current
#'   invocation.
#' @return A character classifier:
#'   \itemize{
#'     \item \code{"no_metadata"} -- run_dir has no metadata; treat as fresh.
#'     \item \code{"match"} -- methodology agrees with stored.
#'     \item \code{"mismatch_active"} -- modes differ, run not finalized.
#'     \item \code{"mismatch_finalized"} -- modes differ, run already finalized;
#'       caller must fork or refuse.
#'   }
#' @export
methodology_mismatch_status <- function(run_dir, config) {
  meta <- read_run_metadata(run_dir)
  if (is.null(meta)) return("no_metadata")
  declared <- config$methodology$mode %||% NA_character_
  stored   <- meta$methodology_mode    %||% NA_character_
  if (identical(declared, stored)) return("match")
  if (isTRUE(meta$is_finalized)) return("mismatch_finalized")
  "mismatch_active"
}

#' Clone a run directory with a new methodology mode
#'
#' Implements the dev/production fork: when a researcher needs to
#' re-analyze the same data under a different methodology, the prior run
#' is preserved (frozen as the original record) and a NEW run directory
#' is created with \code{parent_run_id} pointing at the prior run. The
#' new run inherits nothing from the old run except the linkage in
#' metadata; the new run's outputs are computed fresh.
#'
#' The new run directory is created at \code{new_run_dir} and contains
#' only the initial \code{run_metadata.json}. Pipeline orchestration is
#' the caller's responsibility -- this function does NOT copy data,
#' checkpoints, or any other artifacts from the parent run.
#'
#' @param run_dir Path to the parent run directory (must have a
#'   \code{run_metadata.json}).
#' @param new_mode Methodology mode for the cloned run. Must differ from
#'   the parent's mode (otherwise this is a re-init, not a fork; the
#'   function errors with a helpful message).
#' @param new_run_dir Path to the new run directory (must NOT already
#'   exist; the function refuses to overwrite to avoid accidental
#'   destruction of an active run).
#' @param new_run_id Stable identifier for the new run. Defaults to the
#'   basename of \code{new_run_dir}.
#' @return The new run's metadata list.
#' @export
clone_run_with_new_mode <- function(run_dir, new_mode, new_run_dir,
                                     new_run_id = basename(new_run_dir)) {
  parent_meta <- read_run_metadata(run_dir)
  if (is.null(parent_meta)) {
    stop(sprintf(
      "clone_run_with_new_mode: parent run_dir %s has no run_metadata.json; ",
      run_dir
    ),
    "the parent must have been initialized before it can be cloned. ",
    "Use init_run_state() first.", call. = FALSE)
  }
  if (is.null(parent_meta$methodology_mode)) {
    stop("clone_run_with_new_mode: parent run has NULL methodology_mode; ",
         "nothing to clone-with-new-mode from.", call. = FALSE)
  }
  validate_methodology_mode(new_mode, allow_null = FALSE,
                              caller = "clone_run_with_new_mode")
  if (identical(parent_meta$methodology_mode, new_mode)) {
    stop(sprintf(
      "clone_run_with_new_mode: new_mode '%s' matches parent's mode; ",
      new_mode
    ),
    "this is a re-init, not a fork. No new run is needed.", call. = FALSE)
  }
  if (dir.exists(new_run_dir)) {
    stop(sprintf(
      "clone_run_with_new_mode: %s already exists; refusing to overwrite ",
      new_run_dir
    ),
    "(an active run lives there). Choose a different new_run_dir.",
    call. = FALSE)
  }

  init_run_state(
    run_dir            = new_run_dir,
    run_id             = new_run_id,
    methodology_mode   = new_mode,
    parent_run_id      = parent_meta$run_id,
    mode_changed_from  = parent_meta$methodology_mode
  )
}
